version: '3'
services:
  fastapi-app:
    build:
      context: ./fast_iris  # FastAPI 애플리케이션 경로
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"  # 내부에서 FastAPI 포트 연결
    networks:
      - app-network

  nginx:
    image: nginx:1.26.0  # Nginx 공식 이미지 사용
    container_name: nginx
    ports:
      - "80:80"  # 외부에서 접근하는 포트
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx 설정 파일 마운트
    networks:
      - app-network
      
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Prometheus 설정 파일 마운트
    ports:
      - "9090:9090"  # Prometheus 웹 인터페이스 포트
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"  # Grafana 웹 인터페이스 포트
    networks:
      - app-network  

networks:
  app-network:
