version: '3'

services:
  fastapi-app:
    build:
      context: ./probook  # Dockerfile과 애플리케이션 코드가 위치한 디렉토리
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./probook:/Jiatest/probook  # 호스트의 probook 디렉토리를 컨테이너에 마운트
    environment:
      - PYTHONPATH=/Jiatest
    networks:
      - app-network

  nginx:
    image: nginx:1.26.0
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx 설정 파일 경로
    depends_on:
      - fastapi-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
