version: '3'
services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
